#!/bin/bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output_file="${1:-$project_root/.env}"

ask() {
    local prompt="$1"
    local default="$2"
    local value
    read -r -p "$prompt [$default]: " value
    if [ -z "$value" ]; then
        value="$default"
    fi
    echo "$value"
}

echo "=== L4D2 Env Wizard (MVP) ==="

typechain="$(ask "TYPECHAIN (0=input, 1=docker-user, 2=both)" "0")"
game_ports="$(ask "GAMESERVERPORTS (ej: 27015 o 27015:27020)" "27015")"
tv_ports="$(ask "TVSERVERPORTS (ej: 27020 o 27115:27120)" "27020")"
cmd_limit="$(ask "CMD_LIMIT" "100")"
ssh_ports="$(ask "SSH_PORT" "22")"
whitelist="$(ask "WHITELISTED_IPS (espacio separado)" "")"
udp_allow="$(ask "UDP_ALLOW_PORTS (comma/range, optional)" "")"
tcp_allow="$(ask "TCP_ALLOW_PORTS (comma/range, optional)" "")"
vpn_enabled="$(ask "VPN_ENABLED (true/false)" "false")"
enable_tcp_protect="$(ask "ENABLE_TCP_PROTECT (true/false)" "true")"

docker_input_compat="$(ask "DOCKER_INPUT_COMPAT (true/false)" "false")"
docker_chain_autorecover="$(ask "DOCKER_CHAIN_AUTORECOVER (true/false)" "true")"

cat > "$output_file" <<EOF
# Generated by configure-env.sh
MODULES_ROOT_DIR=""
MODULES_IP_DIR=""
MODULES_NF_DIR=""
MODULES_ONLY=""
MODULES_EXCLUDE=""

TYPECHAIN=${typechain}
DOCKER_INPUT_COMPAT=${docker_input_compat}
DOCKER_CHAIN_AUTORECOVER=${docker_chain_autorecover}
ENABLE_TCP_PROTECT=${enable_tcp_protect}

GAMESERVERPORTS="${game_ports}"
TVSERVERPORTS="${tv_ports}"
CMD_LIMIT=${cmd_limit}
SSH_PORT="${ssh_ports}"
WHITELISTED_IPS="${whitelist}"

UDP_ALLOW_PORTS="${udp_allow}"
TCP_ALLOW_PORTS="${tcp_allow}"

VPN_ENABLED=${vpn_enabled}
VPN_PROTO="udp"
VPN_PORT=1194
VPN_SUBNET="10.8.0.0/24"
VPN_INTERFACE="tun0"
VPN_DOCKER_INTERFACE=""
VPN_LAN_SUBNET="192.168.1.0/24"
VPN_LAN_INTERFACE=""
VPN_ENABLE_NAT=false
VPN_ROUTER_REAL_IP=""
VPN_ROUTER_ALIAS_IP=""
VPN_LOG_ENABLED=false
VPN_LOG_PREFIX="VPN_TRAFFIC: "

LOG_PREFIX_INVALID_SIZE="INVALID_SIZE: "
LOG_PREFIX_MALFORMED="MALFORMED: "
LOG_PREFIX_A2S_INFO="A2S_INFO_FLOOD: "
LOG_PREFIX_A2S_PLAYERS="A2S_PLAYERS_FLOOD: "
LOG_PREFIX_A2S_RULES="A2S_RULES_FLOOD: "
LOG_PREFIX_STEAM_GROUP="STEAM_GROUP_FLOOD: "
LOG_PREFIX_L4D2_CONNECT="L4D2_CONNECT_FLOOD: "
LOG_PREFIX_L4D2_RESERVE="L4D2_RESERVE_FLOOD: "
LOG_PREFIX_UDP_NEW_LIMIT="UDP_NEW_LIMIT: "
LOG_PREFIX_UDP_EST_LIMIT="UDP_EST_LIMIT: "
LOG_PREFIX_TCP_RCON_BLOCK="TCP_RCON_BLOCK: "
LOG_PREFIX_ICMP_FLOOD="ICMP_FLOOD: "

LOGFILE=/var/log/l4d2-iptables.log
RSYSLOG_CONF=/etc/rsyslog.d/l4d2-iptables.conf
EOF

echo "OK: .env generated at $output_file"
